### ISSUE TITLE
Switch to webpack

### ISSUE THREAD

**Issue by lozcalver** [bigfork/silverstripe-recipe#7]
https://github.com/AndrewHaine/silverstripe-webpack-theme

I don’t think we should require via composer because:

- Subsequent `composer install`s  will overwrite any modifications with a blank copy of the theme
- We have some opinionated changes to make (scss vs sass, meta tags, possibly linting rules)
- Templates may be namespaced depending on https://github.com/bigfork/silverstripe-recipe/issues/6 (e.g. `themes/default/templates/App/Layout/Page.ss`)

So the way I see it, the options are:

1. Copy everything into `themes/default`, any changes we want to make can be made directly in this module
2. Fork `silverstripe-webpack-theme`, make changes in the fork, install it via composer. To work around the `composer install` issue above, transform it to a `silverstripe-recipe` so that files only get installed once

I’m leaning towards option 1. It’s easier, and for something that’s going to be pretty opinionated I don’t think it makes sense to separate it out (realistically no one except us is ever going to install `bigfork/silverstripe-webpack-theme-recipe` or whatever we’d call it)

Thoughts @bigfork/crew?

**Comment by AndrewHaine** [comment]
Awesome!

- I agree composer install is a bad idea, I was contacted by Nicolaas from SunnySideUp when I first started the webpack theme and they are working with separating out the webpack config from all the main theme stuff, I think the goal was to create an 'engine' which could be updated separately without overriding the main theme - might be worth looking at (I haven't yet had a chance and it looks like a WIP) -  [Their repo](https://github.com/sunnysideup/silverstripe-sswebpack_engine_only)

- On the opinionated changes i'm fine with whatever the general consensus is I guess we can work on this as we go - one note is that the sass linting rules will have different names as the webpack theme uses stylelint rather than the ruby plugin we have in gulp.

- On the namespacing issue won't we run into problems if we namespace the ```Page``` class? For instance if it is used by a module like Blog. The way I've been working is to leave Page global (and in the top level of ```/templates/```) then namespace subclasses and create the directory ```templates/[Namespace]/(Layout|Includes)/```

- I prefer option 1 too in order to keep everything in one place.

**Comment by lozcalver** [comment]
> On the namespacing issue won't we run into problems if we namespace the `Page` class? For instance if it is used by a module like Blog. The way I've been working is to leave Page global (and in the top level of `/templates/`) then namespace subclasses and create the directory `templates/[Namespace]/(Layout|Includes)/`

Yeah it’s still a necessary evil to have a un-namespaced `Page` class, so I think we’ll always have a structure that ends up a bit messy because of that 😞:

```
themes/
  default/
    templates/
      App/
        Layout/
          ContactPage.ss
          HomePage.ss
      Layout/
        Page.ss
      SilverStripe/
        Blog/
          Model/
            Layout/
              Blog.ss
              BlogPost.ss
      Page.ss
```

**Comment by lozcalver** [comment]
It only took a year, but I’ve had a stab at this - using [Laravel Mix](https://laravel-mix.com/) because I don’t understand _actual_ Webpack enough to work with it directly 😬. Seems to all be fine, but I intend to give it some real-world testing by swapping a couple of existing projects over to it and checking how everything turns out. WIP branch is [here](https://github.com/bigfork/silverstripe-recipe/tree/mix), main differences in day-to-day use are:

- The commands to run are different:
    - `npm run dev` (or `development`) - fast compilation, doesn’t prefix CSS or minify
    - `npm run watch` - same as old watch task, doesn’t prefix/minify
    - `npm run prod` (or `production`) - slower build which does prefix & minify etc
- Files live in a different place:
    - `themes/default/src` - contains all the stuff you actually edit
    - `themes/default/dist` - contains the combined/minified stuff. This is the only directory from the theme that gets exposed
    - `themes/default/src/images` will be copied across to `dist` + compressed en-route
    - `themes/default/src/webfonts` if you have any fonts to copy to `dist`
